### PR TITLE
Fru paqx code refactoring

### PR DESCRIPTION
**Pull request by kushagra-mahajan**
- [X ] I have read the [CONTRIBUTION GUIDE][contributing]
- [ ] This is a bug
- [ ] This is a feature request
- [X ] This is a syntax/style fix
- [X ] This is an improvement to code quality

---

Provide a clear description of changes:
 
[contributing]: http://dellemc-symphony.readthedocs.io/en/latest/contributingtosymphony.html

### CODE REVIEW

**Comment by king-jam** [comment]
Where the unit tests at???

**Comment by ekaley** [comment]
looking into merging this into @Paul-Vincent and my long running changes.  Per the new LRT implementation, some of this refactor will have to be reverted.  @kushagra-mahajan i am trying to cherry pick your refactor around the capability lookup into pauls longrunning branch.

Should hold off on merging this for now.  May be superseded by LRT PR (which is incoming)

**Comment by ekaley** [comment]
https://github.com/dellemc-symphony/fru-paqx-parent/pull/20 should supersede this.

Need careful review from @kushagra-mahajan and @Paul-Vincent to make sure everything made it.

**Comment by kushagra-mahajan** [comment]
Merged with the other PR, so closing this PR.

**Pull request closed without merging**
